
### site meta

title: ipsum plus+
description: lorem ipsum text for the rest of us
author: me


### host settings

# omitting http:// at the start forces HTTPS
domain: eliranmal.github.io
url: https://eliranmal.github.io
baseurl: /ipsum-plus


### site settings
permalink: pretty
google_analytics: 'G-CRK2H2Q7DR'



### build settings

theme: jekyll-theme-minimal
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
