
### site meta

title: ipsum plus+
#description: ipsum text for the rest of us
author: me


### host settings

# omitting http:// at the start forces HTTPS
domain: eliranmal.github.io
url: https://eliranmal.github.io
baseurl: /ipsum-plus
permalink: pretty


### site structure



### build settings

theme: jekyll-theme-minimal
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
